<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="de_DE">
<context>
    <name>NotesManager</name>
    <message>
        <location filename="NotesManager.ui" line="14"/>
        <location filename="NotesManager.ui" line="14"/>
        <source>NotesManager</source>
        <translation>Mitschriften</translation>
    </message>
    <message>
        <location filename="NotesManager.ui" line="55"/>
        <location filename="NotesManager.ui" line="55"/>
        <source>Add Topic</source>
        <translation>Fach hinzufügen</translation>
    </message>
    <message>
        <location filename="NotesManager.ui" line="102"/>
        <location filename="NotesManager.ui" line="133"/>
        <location filename="NotesManager.ui" line="164"/>
        <location filename="NotesManager.ui" line="102"/>
        <source>A</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="NotesManager.ui" line="256"/>
        <location filename="NotesManager.ui" line="256"/>
        <source>Enter passcode to unlock:</source>
        <translation>PIN eingeben:</translation>
    </message>
    <message>
        <location filename="NotesManager.ui" line="298"/>
        <location filename="NotesManager.ui" line="298"/>
        <source>Lock</source>
        <translation>Sperren</translation>
    </message>
    <message>
        <location filename="NotesManager.cpp" line="201"/>
        <location filename="NotesManager.cpp" line="201"/>
        <location filename="NotesManager.cpp" line="201"/>
        <location filename="NotesManager.cpp" line="201"/>
        <location filename="NotesManager.cpp" line="201"/>
        <location filename="NotesManager.cpp" line="213"/>
        <location filename="NotesManager.cpp" line="213"/>
        <location filename="NotesManager.cpp" line="213"/>
        <location filename="NotesManager.cpp" line="213"/>
        <location filename="NotesManager.cpp" line="213"/>
        <location filename="NotesManager.cpp" line="213"/>
        <location filename="NotesManager.cpp" line="213"/>
        <location filename="NotesManager.cpp" line="213"/>
        <location filename="NotesManager.cpp" line="213"/>
        <location filename="NotesManager.cpp" line="213"/>
        <location filename="NotesManager.cpp" line="217"/>
        <location filename="NotesManager.cpp" line="217"/>
        <location filename="NotesManager.cpp" line="217"/>
        <location filename="NotesManager.cpp" line="217"/>
        <location filename="NotesManager.cpp" line="217"/>
        <location filename="NotesManager.cpp" line="217"/>
        <location filename="NotesManager.cpp" line="217"/>
        <location filename="NotesManager.cpp" line="217"/>
        <location filename="NotesManager.cpp" line="219"/>
        <location filename="NotesManager.cpp" line="219"/>
        <location filename="NotesManager.cpp" line="219"/>
        <location filename="NotesManager.cpp" line="219"/>
        <location filename="NotesManager.cpp" line="219"/>
        <location filename="NotesManager.cpp" line="219"/>
        <location filename="NotesManager.cpp" line="219"/>
        <location filename="NotesManager.cpp" line="219"/>
        <location filename="NotesManager.cpp" line="219"/>
        <location filename="NotesManager.cpp" line="221"/>
        <location filename="NotesManager.cpp" line="221"/>
        <location filename="NotesManager.cpp" line="221"/>
        <location filename="NotesManager.cpp" line="221"/>
        <location filename="NotesManager.cpp" line="221"/>
        <location filename="NotesManager.cpp" line="221"/>
        <location filename="NotesManager.cpp" line="221"/>
        <location filename="NotesManager.cpp" line="221"/>
        <location filename="NotesManager.cpp" line="221"/>
        <location filename="NotesManager.cpp" line="221"/>
        <location filename="NotesManager.cpp" line="223"/>
        <location filename="NotesManager.cpp" line="223"/>
        <location filename="NotesManager.cpp" line="223"/>
        <location filename="NotesManager.cpp" line="223"/>
        <location filename="NotesManager.cpp" line="223"/>
        <location filename="NotesManager.cpp" line="223"/>
        <location filename="NotesManager.cpp" line="225"/>
        <location filename="NotesManager.cpp" line="225"/>
        <location filename="NotesManager.cpp" line="225"/>
        <location filename="NotesManager.cpp" line="241"/>
        <location filename="NotesManager.cpp" line="241"/>
        <location filename="NotesManager.cpp" line="241"/>
        <location filename="NotesManager.cpp" line="241"/>
        <location filename="NotesManager.cpp" line="241"/>
        <location filename="NotesManager.cpp" line="241"/>
        <location filename="NotesManager.cpp" line="241"/>
        <location filename="NotesManager.cpp" line="241"/>
        <location filename="NotesManager.cpp" line="241"/>
        <location filename="NotesManager.cpp" line="241"/>
        <location filename="NotesManager.cpp" line="241"/>
        <location filename="NotesManager.cpp" line="241"/>
        <location filename="NotesManager.cpp" line="241"/>
        <location filename="NotesManager.cpp" line="241"/>
        <location filename="NotesManager.cpp" line="241"/>
        <location filename="NotesManager.cpp" line="241"/>
        <location filename="NotesManager.cpp" line="241"/>
        <location filename="NotesManager.cpp" line="241"/>
        <location filename="NotesManager.cpp" line="241"/>
        <location filename="NotesManager.cpp" line="241"/>
        <location filename="NotesManager.cpp" line="241"/>
        <location filename="NotesManager.cpp" line="241"/>
        <location filename="NotesManager.cpp" line="241"/>
        <location filename="NotesManager.cpp" line="241"/>
        <location filename="NotesManager.cpp" line="241"/>
        <location filename="NotesManager.cpp" line="241"/>
        <location filename="NotesManager.cpp" line="241"/>
        <location filename="NotesManager.cpp" line="241"/>
        <location filename="NotesManager.cpp" line="241"/>
        <location filename="NotesManager.cpp" line="241"/>
        <location filename="NotesManager.cpp" line="241"/>
        <location filename="NotesManager.cpp" line="241"/>
        <location filename="NotesManager.cpp" line="241"/>
        <location filename="NotesManager.cpp" line="241"/>
        <location filename="NotesManager.cpp" line="241"/>
        <location filename="NotesManager.cpp" line="241"/>
        <location filename="NotesManager.cpp" line="241"/>
        <location filename="NotesManager.cpp" line="241"/>
        <location filename="NotesManager.cpp" line="241"/>
        <location filename="NotesManager.cpp" line="241"/>
        <location filename="NotesManager.cpp" line="241"/>
        <location filename="NotesManager.cpp" line="241"/>
        <location filename="NotesManager.cpp" line="241"/>
        <location filename="NotesManager.cpp" line="241"/>
        <location filename="NotesManager.cpp" line="241"/>
        <location filename="NotesManager.cpp" line="241"/>
        <location filename="NotesManager.cpp" line="232"/>
        <location filename="NotesManager.cpp" line="232"/>
        <location filename="NotesManager.cpp" line="232"/>
        <location filename="NotesManager.cpp" line="223"/>
        <location filename="NotesManager.cpp" line="223"/>
        <location filename="NotesManager.cpp" line="223"/>
        <location filename="NotesManager.cpp" line="223"/>
        <location filename="NotesManager.cpp" line="223"/>
        <location filename="NotesManager.cpp" line="223"/>
        <location filename="NotesManager.cpp" line="223"/>
        <location filename="NotesManager.cpp" line="236"/>
        <location filename="NotesManager.cpp" line="236"/>
        <location filename="NotesManager.cpp" line="237"/>
        <location filename="NotesManager.cpp" line="237"/>
        <location filename="NotesManager.cpp" line="258"/>
        <location filename="NotesManager.cpp" line="258"/>
        <location filename="NotesManager.cpp" line="259"/>
        <location filename="NotesManager.cpp" line="259"/>
        <location filename="NotesManager.cpp" line="260"/>
        <location filename="NotesManager.cpp" line="260"/>
        <location filename="NotesManager.cpp" line="263"/>
        <location filename="NotesManager.cpp" line="284"/>
        <location filename="NotesManager.cpp" line="284"/>
        <location filename="NotesManager.cpp" line="284"/>
        <location filename="NotesManager.cpp" line="281"/>
        <location filename="NotesManager.cpp" line="281"/>
        <location filename="NotesManager.cpp" line="281"/>
        <location filename="NotesManager.cpp" line="281"/>
        <location filename="NotesManager.cpp" line="281"/>
        <location filename="NotesManager.cpp" line="281"/>
        <location filename="NotesManager.cpp" line="285"/>
        <location filename="NotesManager.cpp" line="285"/>
        <location filename="NotesManager.cpp" line="285"/>
        <location filename="NotesManager.cpp" line="286"/>
        <location filename="NotesManager.cpp" line="286"/>
        <location filename="NotesManager.cpp" line="286"/>
        <location filename="NotesManager.cpp" line="286"/>
        <location filename="NotesManager.cpp" line="286"/>
        <location filename="NotesManager.cpp" line="286"/>
        <location filename="NotesManager.cpp" line="286"/>
        <location filename="NotesManager.cpp" line="286"/>
        <location filename="NotesManager.cpp" line="287"/>
        <location filename="NotesManager.cpp" line="287"/>
        <location filename="NotesManager.cpp" line="289"/>
        <location filename="NotesManager.cpp" line="289"/>
        <location filename="NotesManager.cpp" line="288"/>
        <location filename="NotesManager.cpp" line="287"/>
        <location filename="NotesManager.cpp" line="287"/>
        <location filename="NotesManager.cpp" line="287"/>
        <location filename="NotesManager.cpp" line="289"/>
        <location filename="NotesManager.cpp" line="289"/>
        <location filename="NotesManager.cpp" line="291"/>
        <location filename="NotesManager.cpp" line="291"/>
        <location filename="NotesManager.cpp" line="291"/>
        <location filename="NotesManager.cpp" line="291"/>
        <location filename="NotesManager.cpp" line="289"/>
        <location filename="NotesManager.cpp" line="289"/>
        <location filename="NotesManager.cpp" line="296"/>
        <location filename="NotesManager.cpp" line="296"/>
        <location filename="NotesManager.cpp" line="296"/>
        <location filename="NotesManager.cpp" line="296"/>
        <location filename="NotesManager.cpp" line="292"/>
        <location filename="NotesManager.cpp" line="292"/>
        <location filename="NotesManager.cpp" line="292"/>
        <location filename="NotesManager.cpp" line="292"/>
        <location filename="NotesManager.cpp" line="292"/>
        <location filename="NotesManager.cpp" line="292"/>
        <location filename="NotesManager.cpp" line="292"/>
        <location filename="NotesManager.cpp" line="292"/>
        <location filename="NotesManager.cpp" line="292"/>
        <location filename="NotesManager.cpp" line="292"/>
        <location filename="NotesManager.cpp" line="292"/>
        <location filename="NotesManager.cpp" line="292"/>
        <location filename="NotesManager.cpp" line="292"/>
        <location filename="NotesManager.cpp" line="292"/>
        <location filename="NotesManager.cpp" line="292"/>
        <location filename="NotesManager.cpp" line="292"/>
        <location filename="NotesManager.cpp" line="292"/>
        <location filename="NotesManager.cpp" line="292"/>
        <location filename="NotesManager.cpp" line="292"/>
        <location filename="NotesManager.cpp" line="292"/>
        <location filename="NotesManager.cpp" line="292"/>
        <location filename="NotesManager.cpp" line="292"/>
        <location filename="NotesManager.cpp" line="292"/>
        <location filename="NotesManager.cpp" line="292"/>
        <location filename="NotesManager.cpp" line="292"/>
        <location filename="NotesManager.cpp" line="292"/>
        <location filename="NotesManager.cpp" line="292"/>
        <location filename="NotesManager.cpp" line="300"/>
        <location filename="NotesManager.cpp" line="308"/>
        <location filename="NotesManager.cpp" line="308"/>
        <location filename="NotesManager.cpp" line="309"/>
        <location filename="NotesManager.cpp" line="309"/>
        <location filename="NotesManager.cpp" line="306"/>
        <location filename="NotesManager.cpp" line="306"/>
        <location filename="NotesManager.cpp" line="310"/>
        <location filename="NotesManager.cpp" line="310"/>
        <location filename="NotesManager.cpp" line="310"/>
        <location filename="NotesManager.cpp" line="310"/>
        <location filename="NotesManager.cpp" line="310"/>
        <location filename="NotesManager.cpp" line="310"/>
        <location filename="NotesManager.cpp" line="310"/>
        <location filename="NotesManager.cpp" line="308"/>
        <location filename="NotesManager.cpp" line="308"/>
        <location filename="NotesManager.cpp" line="312"/>
        <location filename="NotesManager.cpp" line="312"/>
        <location filename="NotesManager.cpp" line="314"/>
        <location filename="NotesManager.cpp" line="314"/>
        <location filename="NotesManager.cpp" line="319"/>
        <location filename="NotesManager.cpp" line="319"/>
        <location filename="NotesManager.cpp" line="318"/>
        <location filename="NotesManager.cpp" line="318"/>
        <location filename="NotesManager.cpp" line="318"/>
        <location filename="NotesManager.cpp" line="320"/>
        <location filename="NotesManager.cpp" line="320"/>
        <location filename="NotesManager.cpp" line="318"/>
        <location filename="NotesManager.cpp" line="318"/>
        <location filename="NotesManager.cpp" line="320"/>
        <location filename="NotesManager.cpp" line="320"/>
        <location filename="NotesManager.cpp" line="321"/>
        <location filename="NotesManager.cpp" line="300"/>
        <location filename="NotesManager.cpp" line="296"/>
        <location filename="NotesManager.cpp" line="296"/>
        <source>Topic</source>
        <translation>Unterrichtsfach</translation>
    </message>
    <message>
        <location filename="NotesManager.cpp" line="221"/>
        <location filename="NotesManager.cpp" line="221"/>
        <location filename="NotesManager.cpp" line="221"/>
        <location filename="NotesManager.cpp" line="221"/>
        <location filename="NotesManager.cpp" line="221"/>
        <location filename="NotesManager.cpp" line="233"/>
        <location filename="NotesManager.cpp" line="233"/>
        <location filename="NotesManager.cpp" line="233"/>
        <location filename="NotesManager.cpp" line="233"/>
        <location filename="NotesManager.cpp" line="233"/>
        <location filename="NotesManager.cpp" line="233"/>
        <location filename="NotesManager.cpp" line="233"/>
        <location filename="NotesManager.cpp" line="233"/>
        <location filename="NotesManager.cpp" line="233"/>
        <location filename="NotesManager.cpp" line="233"/>
        <location filename="NotesManager.cpp" line="237"/>
        <location filename="NotesManager.cpp" line="237"/>
        <location filename="NotesManager.cpp" line="237"/>
        <location filename="NotesManager.cpp" line="237"/>
        <location filename="NotesManager.cpp" line="237"/>
        <location filename="NotesManager.cpp" line="237"/>
        <location filename="NotesManager.cpp" line="237"/>
        <location filename="NotesManager.cpp" line="237"/>
        <location filename="NotesManager.cpp" line="239"/>
        <location filename="NotesManager.cpp" line="239"/>
        <location filename="NotesManager.cpp" line="239"/>
        <location filename="NotesManager.cpp" line="239"/>
        <location filename="NotesManager.cpp" line="239"/>
        <location filename="NotesManager.cpp" line="239"/>
        <location filename="NotesManager.cpp" line="239"/>
        <location filename="NotesManager.cpp" line="239"/>
        <location filename="NotesManager.cpp" line="239"/>
        <location filename="NotesManager.cpp" line="241"/>
        <location filename="NotesManager.cpp" line="241"/>
        <location filename="NotesManager.cpp" line="241"/>
        <location filename="NotesManager.cpp" line="241"/>
        <location filename="NotesManager.cpp" line="241"/>
        <location filename="NotesManager.cpp" line="241"/>
        <location filename="NotesManager.cpp" line="241"/>
        <location filename="NotesManager.cpp" line="241"/>
        <location filename="NotesManager.cpp" line="241"/>
        <location filename="NotesManager.cpp" line="241"/>
        <location filename="NotesManager.cpp" line="243"/>
        <location filename="NotesManager.cpp" line="243"/>
        <location filename="NotesManager.cpp" line="243"/>
        <location filename="NotesManager.cpp" line="243"/>
        <location filename="NotesManager.cpp" line="243"/>
        <location filename="NotesManager.cpp" line="243"/>
        <location filename="NotesManager.cpp" line="245"/>
        <location filename="NotesManager.cpp" line="245"/>
        <location filename="NotesManager.cpp" line="245"/>
        <location filename="NotesManager.cpp" line="265"/>
        <location filename="NotesManager.cpp" line="265"/>
        <location filename="NotesManager.cpp" line="265"/>
        <location filename="NotesManager.cpp" line="265"/>
        <location filename="NotesManager.cpp" line="265"/>
        <location filename="NotesManager.cpp" line="265"/>
        <location filename="NotesManager.cpp" line="265"/>
        <location filename="NotesManager.cpp" line="265"/>
        <location filename="NotesManager.cpp" line="265"/>
        <location filename="NotesManager.cpp" line="265"/>
        <location filename="NotesManager.cpp" line="265"/>
        <location filename="NotesManager.cpp" line="265"/>
        <location filename="NotesManager.cpp" line="265"/>
        <location filename="NotesManager.cpp" line="265"/>
        <location filename="NotesManager.cpp" line="265"/>
        <location filename="NotesManager.cpp" line="265"/>
        <location filename="NotesManager.cpp" line="265"/>
        <location filename="NotesManager.cpp" line="265"/>
        <location filename="NotesManager.cpp" line="265"/>
        <location filename="NotesManager.cpp" line="265"/>
        <location filename="NotesManager.cpp" line="265"/>
        <location filename="NotesManager.cpp" line="265"/>
        <location filename="NotesManager.cpp" line="265"/>
        <location filename="NotesManager.cpp" line="265"/>
        <location filename="NotesManager.cpp" line="265"/>
        <location filename="NotesManager.cpp" line="265"/>
        <location filename="NotesManager.cpp" line="265"/>
        <location filename="NotesManager.cpp" line="265"/>
        <location filename="NotesManager.cpp" line="265"/>
        <location filename="NotesManager.cpp" line="265"/>
        <location filename="NotesManager.cpp" line="265"/>
        <location filename="NotesManager.cpp" line="265"/>
        <location filename="NotesManager.cpp" line="265"/>
        <location filename="NotesManager.cpp" line="265"/>
        <location filename="NotesManager.cpp" line="265"/>
        <location filename="NotesManager.cpp" line="265"/>
        <location filename="NotesManager.cpp" line="265"/>
        <location filename="NotesManager.cpp" line="265"/>
        <location filename="NotesManager.cpp" line="265"/>
        <location filename="NotesManager.cpp" line="265"/>
        <location filename="NotesManager.cpp" line="265"/>
        <location filename="NotesManager.cpp" line="265"/>
        <location filename="NotesManager.cpp" line="265"/>
        <location filename="NotesManager.cpp" line="265"/>
        <location filename="NotesManager.cpp" line="265"/>
        <location filename="NotesManager.cpp" line="265"/>
        <location filename="NotesManager.cpp" line="257"/>
        <location filename="NotesManager.cpp" line="257"/>
        <location filename="NotesManager.cpp" line="257"/>
        <location filename="NotesManager.cpp" line="248"/>
        <location filename="NotesManager.cpp" line="248"/>
        <location filename="NotesManager.cpp" line="248"/>
        <location filename="NotesManager.cpp" line="248"/>
        <location filename="NotesManager.cpp" line="248"/>
        <location filename="NotesManager.cpp" line="248"/>
        <location filename="NotesManager.cpp" line="248"/>
        <location filename="NotesManager.cpp" line="261"/>
        <location filename="NotesManager.cpp" line="261"/>
        <location filename="NotesManager.cpp" line="262"/>
        <location filename="NotesManager.cpp" line="262"/>
        <location filename="NotesManager.cpp" line="283"/>
        <location filename="NotesManager.cpp" line="283"/>
        <location filename="NotesManager.cpp" line="284"/>
        <location filename="NotesManager.cpp" line="284"/>
        <location filename="NotesManager.cpp" line="285"/>
        <location filename="NotesManager.cpp" line="285"/>
        <location filename="NotesManager.cpp" line="288"/>
        <location filename="NotesManager.cpp" line="309"/>
        <location filename="NotesManager.cpp" line="309"/>
        <location filename="NotesManager.cpp" line="309"/>
        <location filename="NotesManager.cpp" line="306"/>
        <location filename="NotesManager.cpp" line="306"/>
        <location filename="NotesManager.cpp" line="306"/>
        <location filename="NotesManager.cpp" line="306"/>
        <location filename="NotesManager.cpp" line="306"/>
        <location filename="NotesManager.cpp" line="306"/>
        <location filename="NotesManager.cpp" line="310"/>
        <location filename="NotesManager.cpp" line="310"/>
        <location filename="NotesManager.cpp" line="310"/>
        <location filename="NotesManager.cpp" line="311"/>
        <location filename="NotesManager.cpp" line="311"/>
        <location filename="NotesManager.cpp" line="311"/>
        <location filename="NotesManager.cpp" line="311"/>
        <location filename="NotesManager.cpp" line="311"/>
        <location filename="NotesManager.cpp" line="311"/>
        <location filename="NotesManager.cpp" line="311"/>
        <location filename="NotesManager.cpp" line="311"/>
        <location filename="NotesManager.cpp" line="312"/>
        <location filename="NotesManager.cpp" line="312"/>
        <location filename="NotesManager.cpp" line="314"/>
        <location filename="NotesManager.cpp" line="314"/>
        <location filename="NotesManager.cpp" line="313"/>
        <location filename="NotesManager.cpp" line="312"/>
        <location filename="NotesManager.cpp" line="312"/>
        <location filename="NotesManager.cpp" line="312"/>
        <location filename="NotesManager.cpp" line="314"/>
        <location filename="NotesManager.cpp" line="314"/>
        <location filename="NotesManager.cpp" line="316"/>
        <location filename="NotesManager.cpp" line="316"/>
        <location filename="NotesManager.cpp" line="316"/>
        <location filename="NotesManager.cpp" line="316"/>
        <location filename="NotesManager.cpp" line="314"/>
        <location filename="NotesManager.cpp" line="314"/>
        <location filename="NotesManager.cpp" line="321"/>
        <location filename="NotesManager.cpp" line="321"/>
        <location filename="NotesManager.cpp" line="321"/>
        <location filename="NotesManager.cpp" line="321"/>
        <location filename="NotesManager.cpp" line="317"/>
        <location filename="NotesManager.cpp" line="317"/>
        <location filename="NotesManager.cpp" line="317"/>
        <location filename="NotesManager.cpp" line="317"/>
        <location filename="NotesManager.cpp" line="317"/>
        <location filename="NotesManager.cpp" line="317"/>
        <location filename="NotesManager.cpp" line="317"/>
        <location filename="NotesManager.cpp" line="317"/>
        <location filename="NotesManager.cpp" line="317"/>
        <location filename="NotesManager.cpp" line="317"/>
        <location filename="NotesManager.cpp" line="317"/>
        <location filename="NotesManager.cpp" line="317"/>
        <location filename="NotesManager.cpp" line="317"/>
        <location filename="NotesManager.cpp" line="317"/>
        <location filename="NotesManager.cpp" line="317"/>
        <location filename="NotesManager.cpp" line="317"/>
        <location filename="NotesManager.cpp" line="317"/>
        <location filename="NotesManager.cpp" line="317"/>
        <location filename="NotesManager.cpp" line="317"/>
        <location filename="NotesManager.cpp" line="317"/>
        <location filename="NotesManager.cpp" line="317"/>
        <location filename="NotesManager.cpp" line="317"/>
        <location filename="NotesManager.cpp" line="317"/>
        <location filename="NotesManager.cpp" line="317"/>
        <location filename="NotesManager.cpp" line="317"/>
        <location filename="NotesManager.cpp" line="317"/>
        <location filename="NotesManager.cpp" line="317"/>
        <location filename="NotesManager.cpp" line="325"/>
        <location filename="NotesManager.cpp" line="333"/>
        <location filename="NotesManager.cpp" line="333"/>
        <location filename="NotesManager.cpp" line="334"/>
        <location filename="NotesManager.cpp" line="334"/>
        <location filename="NotesManager.cpp" line="331"/>
        <location filename="NotesManager.cpp" line="331"/>
        <location filename="NotesManager.cpp" line="335"/>
        <location filename="NotesManager.cpp" line="335"/>
        <location filename="NotesManager.cpp" line="335"/>
        <location filename="NotesManager.cpp" line="335"/>
        <location filename="NotesManager.cpp" line="335"/>
        <location filename="NotesManager.cpp" line="335"/>
        <location filename="NotesManager.cpp" line="335"/>
        <location filename="NotesManager.cpp" line="333"/>
        <location filename="NotesManager.cpp" line="333"/>
        <location filename="NotesManager.cpp" line="337"/>
        <location filename="NotesManager.cpp" line="337"/>
        <location filename="NotesManager.cpp" line="339"/>
        <location filename="NotesManager.cpp" line="339"/>
        <location filename="NotesManager.cpp" line="344"/>
        <location filename="NotesManager.cpp" line="344"/>
        <location filename="NotesManager.cpp" line="343"/>
        <location filename="NotesManager.cpp" line="343"/>
        <location filename="NotesManager.cpp" line="343"/>
        <location filename="NotesManager.cpp" line="345"/>
        <location filename="NotesManager.cpp" line="345"/>
        <location filename="NotesManager.cpp" line="343"/>
        <location filename="NotesManager.cpp" line="343"/>
        <location filename="NotesManager.cpp" line="345"/>
        <location filename="NotesManager.cpp" line="345"/>
        <location filename="NotesManager.cpp" line="346"/>
        <location filename="NotesManager.cpp" line="325"/>
        <location filename="NotesManager.cpp" line="321"/>
        <location filename="NotesManager.cpp" line="321"/>
        <source>Saved: %1</source>
        <translation>Gespeichert: %1</translation>
    </message>
    <message>
        <location filename="NotesManager.cpp" line="222"/>
        <location filename="NotesManager.cpp" line="222"/>
        <location filename="NotesManager.cpp" line="222"/>
        <location filename="NotesManager.cpp" line="222"/>
        <location filename="NotesManager.cpp" line="222"/>
        <location filename="NotesManager.cpp" line="234"/>
        <location filename="NotesManager.cpp" line="234"/>
        <location filename="NotesManager.cpp" line="234"/>
        <location filename="NotesManager.cpp" line="234"/>
        <location filename="NotesManager.cpp" line="234"/>
        <location filename="NotesManager.cpp" line="234"/>
        <location filename="NotesManager.cpp" line="234"/>
        <location filename="NotesManager.cpp" line="234"/>
        <location filename="NotesManager.cpp" line="234"/>
        <location filename="NotesManager.cpp" line="234"/>
        <location filename="NotesManager.cpp" line="238"/>
        <location filename="NotesManager.cpp" line="238"/>
        <location filename="NotesManager.cpp" line="238"/>
        <location filename="NotesManager.cpp" line="238"/>
        <location filename="NotesManager.cpp" line="238"/>
        <location filename="NotesManager.cpp" line="238"/>
        <location filename="NotesManager.cpp" line="238"/>
        <location filename="NotesManager.cpp" line="238"/>
        <location filename="NotesManager.cpp" line="240"/>
        <location filename="NotesManager.cpp" line="240"/>
        <location filename="NotesManager.cpp" line="240"/>
        <location filename="NotesManager.cpp" line="240"/>
        <location filename="NotesManager.cpp" line="240"/>
        <location filename="NotesManager.cpp" line="240"/>
        <location filename="NotesManager.cpp" line="240"/>
        <location filename="NotesManager.cpp" line="240"/>
        <location filename="NotesManager.cpp" line="240"/>
        <location filename="NotesManager.cpp" line="242"/>
        <location filename="NotesManager.cpp" line="242"/>
        <location filename="NotesManager.cpp" line="242"/>
        <location filename="NotesManager.cpp" line="242"/>
        <location filename="NotesManager.cpp" line="242"/>
        <location filename="NotesManager.cpp" line="242"/>
        <location filename="NotesManager.cpp" line="242"/>
        <location filename="NotesManager.cpp" line="242"/>
        <location filename="NotesManager.cpp" line="242"/>
        <location filename="NotesManager.cpp" line="242"/>
        <location filename="NotesManager.cpp" line="244"/>
        <location filename="NotesManager.cpp" line="244"/>
        <location filename="NotesManager.cpp" line="244"/>
        <location filename="NotesManager.cpp" line="244"/>
        <location filename="NotesManager.cpp" line="244"/>
        <location filename="NotesManager.cpp" line="244"/>
        <location filename="NotesManager.cpp" line="246"/>
        <location filename="NotesManager.cpp" line="246"/>
        <location filename="NotesManager.cpp" line="246"/>
        <location filename="NotesManager.cpp" line="266"/>
        <location filename="NotesManager.cpp" line="266"/>
        <location filename="NotesManager.cpp" line="266"/>
        <location filename="NotesManager.cpp" line="266"/>
        <location filename="NotesManager.cpp" line="266"/>
        <location filename="NotesManager.cpp" line="266"/>
        <location filename="NotesManager.cpp" line="266"/>
        <location filename="NotesManager.cpp" line="266"/>
        <location filename="NotesManager.cpp" line="266"/>
        <location filename="NotesManager.cpp" line="266"/>
        <location filename="NotesManager.cpp" line="266"/>
        <location filename="NotesManager.cpp" line="266"/>
        <location filename="NotesManager.cpp" line="266"/>
        <location filename="NotesManager.cpp" line="266"/>
        <location filename="NotesManager.cpp" line="266"/>
        <location filename="NotesManager.cpp" line="266"/>
        <location filename="NotesManager.cpp" line="266"/>
        <location filename="NotesManager.cpp" line="266"/>
        <location filename="NotesManager.cpp" line="266"/>
        <location filename="NotesManager.cpp" line="266"/>
        <location filename="NotesManager.cpp" line="266"/>
        <location filename="NotesManager.cpp" line="266"/>
        <location filename="NotesManager.cpp" line="266"/>
        <location filename="NotesManager.cpp" line="266"/>
        <location filename="NotesManager.cpp" line="266"/>
        <location filename="NotesManager.cpp" line="266"/>
        <location filename="NotesManager.cpp" line="266"/>
        <location filename="NotesManager.cpp" line="266"/>
        <location filename="NotesManager.cpp" line="266"/>
        <location filename="NotesManager.cpp" line="266"/>
        <location filename="NotesManager.cpp" line="266"/>
        <location filename="NotesManager.cpp" line="266"/>
        <location filename="NotesManager.cpp" line="266"/>
        <location filename="NotesManager.cpp" line="266"/>
        <location filename="NotesManager.cpp" line="266"/>
        <location filename="NotesManager.cpp" line="266"/>
        <location filename="NotesManager.cpp" line="266"/>
        <location filename="NotesManager.cpp" line="266"/>
        <location filename="NotesManager.cpp" line="266"/>
        <location filename="NotesManager.cpp" line="266"/>
        <location filename="NotesManager.cpp" line="266"/>
        <location filename="NotesManager.cpp" line="266"/>
        <location filename="NotesManager.cpp" line="266"/>
        <location filename="NotesManager.cpp" line="266"/>
        <location filename="NotesManager.cpp" line="266"/>
        <location filename="NotesManager.cpp" line="266"/>
        <location filename="NotesManager.cpp" line="258"/>
        <location filename="NotesManager.cpp" line="258"/>
        <location filename="NotesManager.cpp" line="258"/>
        <location filename="NotesManager.cpp" line="249"/>
        <location filename="NotesManager.cpp" line="249"/>
        <location filename="NotesManager.cpp" line="249"/>
        <location filename="NotesManager.cpp" line="249"/>
        <location filename="NotesManager.cpp" line="249"/>
        <location filename="NotesManager.cpp" line="249"/>
        <location filename="NotesManager.cpp" line="249"/>
        <location filename="NotesManager.cpp" line="262"/>
        <location filename="NotesManager.cpp" line="262"/>
        <location filename="NotesManager.cpp" line="263"/>
        <location filename="NotesManager.cpp" line="263"/>
        <location filename="NotesManager.cpp" line="284"/>
        <location filename="NotesManager.cpp" line="284"/>
        <location filename="NotesManager.cpp" line="285"/>
        <location filename="NotesManager.cpp" line="285"/>
        <location filename="NotesManager.cpp" line="286"/>
        <location filename="NotesManager.cpp" line="286"/>
        <location filename="NotesManager.cpp" line="289"/>
        <location filename="NotesManager.cpp" line="310"/>
        <location filename="NotesManager.cpp" line="310"/>
        <location filename="NotesManager.cpp" line="310"/>
        <location filename="NotesManager.cpp" line="307"/>
        <location filename="NotesManager.cpp" line="307"/>
        <location filename="NotesManager.cpp" line="307"/>
        <location filename="NotesManager.cpp" line="307"/>
        <location filename="NotesManager.cpp" line="307"/>
        <location filename="NotesManager.cpp" line="307"/>
        <location filename="NotesManager.cpp" line="311"/>
        <location filename="NotesManager.cpp" line="311"/>
        <location filename="NotesManager.cpp" line="311"/>
        <location filename="NotesManager.cpp" line="312"/>
        <location filename="NotesManager.cpp" line="312"/>
        <location filename="NotesManager.cpp" line="312"/>
        <location filename="NotesManager.cpp" line="312"/>
        <location filename="NotesManager.cpp" line="312"/>
        <location filename="NotesManager.cpp" line="312"/>
        <location filename="NotesManager.cpp" line="312"/>
        <location filename="NotesManager.cpp" line="312"/>
        <location filename="NotesManager.cpp" line="313"/>
        <location filename="NotesManager.cpp" line="313"/>
        <location filename="NotesManager.cpp" line="315"/>
        <location filename="NotesManager.cpp" line="315"/>
        <location filename="NotesManager.cpp" line="314"/>
        <location filename="NotesManager.cpp" line="313"/>
        <location filename="NotesManager.cpp" line="313"/>
        <location filename="NotesManager.cpp" line="313"/>
        <location filename="NotesManager.cpp" line="315"/>
        <location filename="NotesManager.cpp" line="315"/>
        <location filename="NotesManager.cpp" line="317"/>
        <location filename="NotesManager.cpp" line="317"/>
        <location filename="NotesManager.cpp" line="317"/>
        <location filename="NotesManager.cpp" line="317"/>
        <location filename="NotesManager.cpp" line="315"/>
        <location filename="NotesManager.cpp" line="315"/>
        <location filename="NotesManager.cpp" line="322"/>
        <location filename="NotesManager.cpp" line="322"/>
        <location filename="NotesManager.cpp" line="322"/>
        <location filename="NotesManager.cpp" line="322"/>
        <location filename="NotesManager.cpp" line="318"/>
        <location filename="NotesManager.cpp" line="318"/>
        <location filename="NotesManager.cpp" line="318"/>
        <location filename="NotesManager.cpp" line="318"/>
        <location filename="NotesManager.cpp" line="318"/>
        <location filename="NotesManager.cpp" line="318"/>
        <location filename="NotesManager.cpp" line="318"/>
        <location filename="NotesManager.cpp" line="318"/>
        <location filename="NotesManager.cpp" line="318"/>
        <location filename="NotesManager.cpp" line="318"/>
        <location filename="NotesManager.cpp" line="318"/>
        <location filename="NotesManager.cpp" line="318"/>
        <location filename="NotesManager.cpp" line="318"/>
        <location filename="NotesManager.cpp" line="318"/>
        <location filename="NotesManager.cpp" line="318"/>
        <location filename="NotesManager.cpp" line="318"/>
        <location filename="NotesManager.cpp" line="318"/>
        <location filename="NotesManager.cpp" line="318"/>
        <location filename="NotesManager.cpp" line="318"/>
        <location filename="NotesManager.cpp" line="318"/>
        <location filename="NotesManager.cpp" line="318"/>
        <location filename="NotesManager.cpp" line="318"/>
        <location filename="NotesManager.cpp" line="318"/>
        <location filename="NotesManager.cpp" line="318"/>
        <location filename="NotesManager.cpp" line="318"/>
        <location filename="NotesManager.cpp" line="318"/>
        <location filename="NotesManager.cpp" line="318"/>
        <location filename="NotesManager.cpp" line="326"/>
        <location filename="NotesManager.cpp" line="334"/>
        <location filename="NotesManager.cpp" line="334"/>
        <location filename="NotesManager.cpp" line="335"/>
        <location filename="NotesManager.cpp" line="335"/>
        <location filename="NotesManager.cpp" line="332"/>
        <location filename="NotesManager.cpp" line="332"/>
        <location filename="NotesManager.cpp" line="336"/>
        <location filename="NotesManager.cpp" line="336"/>
        <location filename="NotesManager.cpp" line="336"/>
        <location filename="NotesManager.cpp" line="336"/>
        <location filename="NotesManager.cpp" line="336"/>
        <location filename="NotesManager.cpp" line="336"/>
        <location filename="NotesManager.cpp" line="336"/>
        <location filename="NotesManager.cpp" line="334"/>
        <location filename="NotesManager.cpp" line="334"/>
        <location filename="NotesManager.cpp" line="338"/>
        <location filename="NotesManager.cpp" line="338"/>
        <location filename="NotesManager.cpp" line="340"/>
        <location filename="NotesManager.cpp" line="340"/>
        <location filename="NotesManager.cpp" line="345"/>
        <location filename="NotesManager.cpp" line="345"/>
        <location filename="NotesManager.cpp" line="344"/>
        <location filename="NotesManager.cpp" line="344"/>
        <location filename="NotesManager.cpp" line="344"/>
        <location filename="NotesManager.cpp" line="346"/>
        <location filename="NotesManager.cpp" line="346"/>
        <location filename="NotesManager.cpp" line="344"/>
        <location filename="NotesManager.cpp" line="344"/>
        <location filename="NotesManager.cpp" line="346"/>
        <location filename="NotesManager.cpp" line="346"/>
        <location filename="NotesManager.cpp" line="347"/>
        <location filename="NotesManager.cpp" line="326"/>
        <location filename="NotesManager.cpp" line="322"/>
        <location filename="NotesManager.cpp" line="322"/>
        <source>Failed to save: %1</source>
        <translation>Speichern fehlgeschlagen: %1</translation>
    </message>
    <message>
        <location filename="NotesManager.cpp" line="302"/>
        <location filename="NotesManager.cpp" line="303"/>
        <location filename="NotesManager.cpp" line="303"/>
        <location filename="NotesManager.cpp" line="303"/>
        <location filename="NotesManager.cpp" line="304"/>
        <location filename="NotesManager.cpp" line="304"/>
        <location filename="NotesManager.cpp" line="304"/>
        <location filename="NotesManager.cpp" line="304"/>
        <location filename="NotesManager.cpp" line="306"/>
        <location filename="NotesManager.cpp" line="306"/>
        <location filename="NotesManager.cpp" line="306"/>
        <location filename="NotesManager.cpp" line="306"/>
        <location filename="NotesManager.cpp" line="306"/>
        <location filename="NotesManager.cpp" line="306"/>
        <location filename="NotesManager.cpp" line="306"/>
        <location filename="NotesManager.cpp" line="306"/>
        <location filename="NotesManager.cpp" line="306"/>
        <location filename="NotesManager.cpp" line="308"/>
        <location filename="NotesManager.cpp" line="308"/>
        <location filename="NotesManager.cpp" line="308"/>
        <location filename="NotesManager.cpp" line="310"/>
        <location filename="NotesManager.cpp" line="308"/>
        <location filename="NotesManager.cpp" line="308"/>
        <location filename="NotesManager.cpp" line="305"/>
        <location filename="NotesManager.cpp" line="305"/>
        <location filename="NotesManager.cpp" line="305"/>
        <location filename="NotesManager.cpp" line="305"/>
        <location filename="NotesManager.cpp" line="307"/>
        <location filename="NotesManager.cpp" line="307"/>
        <location filename="NotesManager.cpp" line="307"/>
        <location filename="NotesManager.cpp" line="307"/>
        <location filename="NotesManager.cpp" line="307"/>
        <location filename="NotesManager.cpp" line="307"/>
        <location filename="NotesManager.cpp" line="309"/>
        <location filename="NotesManager.cpp" line="309"/>
        <location filename="NotesManager.cpp" line="309"/>
        <location filename="NotesManager.cpp" line="329"/>
        <location filename="NotesManager.cpp" line="329"/>
        <location filename="NotesManager.cpp" line="329"/>
        <location filename="NotesManager.cpp" line="329"/>
        <location filename="NotesManager.cpp" line="329"/>
        <location filename="NotesManager.cpp" line="329"/>
        <location filename="NotesManager.cpp" line="329"/>
        <location filename="NotesManager.cpp" line="329"/>
        <location filename="NotesManager.cpp" line="329"/>
        <location filename="NotesManager.cpp" line="329"/>
        <location filename="NotesManager.cpp" line="329"/>
        <location filename="NotesManager.cpp" line="329"/>
        <location filename="NotesManager.cpp" line="329"/>
        <location filename="NotesManager.cpp" line="329"/>
        <location filename="NotesManager.cpp" line="329"/>
        <location filename="NotesManager.cpp" line="329"/>
        <location filename="NotesManager.cpp" line="329"/>
        <location filename="NotesManager.cpp" line="329"/>
        <location filename="NotesManager.cpp" line="329"/>
        <location filename="NotesManager.cpp" line="329"/>
        <location filename="NotesManager.cpp" line="329"/>
        <location filename="NotesManager.cpp" line="329"/>
        <location filename="NotesManager.cpp" line="329"/>
        <location filename="NotesManager.cpp" line="329"/>
        <location filename="NotesManager.cpp" line="329"/>
        <location filename="NotesManager.cpp" line="329"/>
        <location filename="NotesManager.cpp" line="329"/>
        <location filename="NotesManager.cpp" line="329"/>
        <location filename="NotesManager.cpp" line="329"/>
        <location filename="NotesManager.cpp" line="329"/>
        <location filename="NotesManager.cpp" line="329"/>
        <location filename="NotesManager.cpp" line="329"/>
        <location filename="NotesManager.cpp" line="329"/>
        <location filename="NotesManager.cpp" line="329"/>
        <location filename="NotesManager.cpp" line="329"/>
        <location filename="NotesManager.cpp" line="329"/>
        <location filename="NotesManager.cpp" line="329"/>
        <location filename="NotesManager.cpp" line="329"/>
        <location filename="NotesManager.cpp" line="329"/>
        <location filename="NotesManager.cpp" line="329"/>
        <location filename="NotesManager.cpp" line="329"/>
        <location filename="NotesManager.cpp" line="329"/>
        <location filename="NotesManager.cpp" line="329"/>
        <location filename="NotesManager.cpp" line="329"/>
        <location filename="NotesManager.cpp" line="361"/>
        <location filename="NotesManager.cpp" line="361"/>
        <location filename="NotesManager.cpp" line="308"/>
        <location filename="NotesManager.cpp" line="308"/>
        <location filename="NotesManager.cpp" line="308"/>
        <location filename="NotesManager.cpp" line="299"/>
        <location filename="NotesManager.cpp" line="299"/>
        <location filename="NotesManager.cpp" line="299"/>
        <location filename="NotesManager.cpp" line="299"/>
        <location filename="NotesManager.cpp" line="299"/>
        <location filename="NotesManager.cpp" line="299"/>
        <location filename="NotesManager.cpp" line="299"/>
        <location filename="NotesManager.cpp" line="312"/>
        <location filename="NotesManager.cpp" line="312"/>
        <location filename="NotesManager.cpp" line="313"/>
        <location filename="NotesManager.cpp" line="313"/>
        <location filename="NotesManager.cpp" line="334"/>
        <location filename="NotesManager.cpp" line="334"/>
        <location filename="NotesManager.cpp" line="335"/>
        <location filename="NotesManager.cpp" line="335"/>
        <location filename="NotesManager.cpp" line="336"/>
        <location filename="NotesManager.cpp" line="336"/>
        <location filename="NotesManager.cpp" line="339"/>
        <location filename="NotesManager.cpp" line="360"/>
        <location filename="NotesManager.cpp" line="360"/>
        <location filename="NotesManager.cpp" line="360"/>
        <location filename="NotesManager.cpp" line="357"/>
        <location filename="NotesManager.cpp" line="357"/>
        <location filename="NotesManager.cpp" line="357"/>
        <location filename="NotesManager.cpp" line="357"/>
        <location filename="NotesManager.cpp" line="357"/>
        <location filename="NotesManager.cpp" line="357"/>
        <location filename="NotesManager.cpp" line="361"/>
        <location filename="NotesManager.cpp" line="361"/>
        <location filename="NotesManager.cpp" line="361"/>
        <location filename="NotesManager.cpp" line="362"/>
        <location filename="NotesManager.cpp" line="362"/>
        <location filename="NotesManager.cpp" line="362"/>
        <location filename="NotesManager.cpp" line="362"/>
        <location filename="NotesManager.cpp" line="362"/>
        <location filename="NotesManager.cpp" line="362"/>
        <location filename="NotesManager.cpp" line="362"/>
        <location filename="NotesManager.cpp" line="362"/>
        <location filename="NotesManager.cpp" line="363"/>
        <location filename="NotesManager.cpp" line="363"/>
        <location filename="NotesManager.cpp" line="365"/>
        <location filename="NotesManager.cpp" line="365"/>
        <location filename="NotesManager.cpp" line="364"/>
        <location filename="NotesManager.cpp" line="363"/>
        <location filename="NotesManager.cpp" line="363"/>
        <location filename="NotesManager.cpp" line="363"/>
        <location filename="NotesManager.cpp" line="365"/>
        <location filename="NotesManager.cpp" line="365"/>
        <location filename="NotesManager.cpp" line="367"/>
        <location filename="NotesManager.cpp" line="367"/>
        <location filename="NotesManager.cpp" line="367"/>
        <location filename="NotesManager.cpp" line="367"/>
        <location filename="NotesManager.cpp" line="365"/>
        <location filename="NotesManager.cpp" line="365"/>
        <location filename="NotesManager.cpp" line="372"/>
        <location filename="NotesManager.cpp" line="372"/>
        <location filename="NotesManager.cpp" line="372"/>
        <location filename="NotesManager.cpp" line="372"/>
        <location filename="NotesManager.cpp" line="368"/>
        <location filename="NotesManager.cpp" line="368"/>
        <location filename="NotesManager.cpp" line="368"/>
        <location filename="NotesManager.cpp" line="368"/>
        <location filename="NotesManager.cpp" line="368"/>
        <location filename="NotesManager.cpp" line="368"/>
        <location filename="NotesManager.cpp" line="368"/>
        <location filename="NotesManager.cpp" line="368"/>
        <location filename="NotesManager.cpp" line="368"/>
        <location filename="NotesManager.cpp" line="368"/>
        <location filename="NotesManager.cpp" line="368"/>
        <location filename="NotesManager.cpp" line="368"/>
        <location filename="NotesManager.cpp" line="368"/>
        <location filename="NotesManager.cpp" line="368"/>
        <location filename="NotesManager.cpp" line="368"/>
        <location filename="NotesManager.cpp" line="368"/>
        <location filename="NotesManager.cpp" line="368"/>
        <location filename="NotesManager.cpp" line="368"/>
        <location filename="NotesManager.cpp" line="368"/>
        <location filename="NotesManager.cpp" line="368"/>
        <location filename="NotesManager.cpp" line="368"/>
        <location filename="NotesManager.cpp" line="368"/>
        <location filename="NotesManager.cpp" line="368"/>
        <location filename="NotesManager.cpp" line="368"/>
        <location filename="NotesManager.cpp" line="368"/>
        <location filename="NotesManager.cpp" line="368"/>
        <location filename="NotesManager.cpp" line="368"/>
        <location filename="NotesManager.cpp" line="376"/>
        <location filename="NotesManager.cpp" line="384"/>
        <location filename="NotesManager.cpp" line="384"/>
        <location filename="NotesManager.cpp" line="385"/>
        <location filename="NotesManager.cpp" line="385"/>
        <location filename="NotesManager.cpp" line="382"/>
        <location filename="NotesManager.cpp" line="382"/>
        <location filename="NotesManager.cpp" line="386"/>
        <location filename="NotesManager.cpp" line="386"/>
        <location filename="NotesManager.cpp" line="386"/>
        <location filename="NotesManager.cpp" line="386"/>
        <location filename="NotesManager.cpp" line="386"/>
        <location filename="NotesManager.cpp" line="386"/>
        <location filename="NotesManager.cpp" line="386"/>
        <location filename="NotesManager.cpp" line="384"/>
        <location filename="NotesManager.cpp" line="384"/>
        <location filename="NotesManager.cpp" line="388"/>
        <location filename="NotesManager.cpp" line="388"/>
        <location filename="NotesManager.cpp" line="390"/>
        <location filename="NotesManager.cpp" line="390"/>
        <location filename="NotesManager.cpp" line="395"/>
        <location filename="NotesManager.cpp" line="395"/>
        <location filename="NotesManager.cpp" line="394"/>
        <location filename="NotesManager.cpp" line="394"/>
        <location filename="NotesManager.cpp" line="394"/>
        <location filename="NotesManager.cpp" line="396"/>
        <location filename="NotesManager.cpp" line="396"/>
        <location filename="NotesManager.cpp" line="394"/>
        <location filename="NotesManager.cpp" line="394"/>
        <location filename="NotesManager.cpp" line="396"/>
        <location filename="NotesManager.cpp" line="396"/>
        <location filename="NotesManager.cpp" line="397"/>
        <location filename="NotesManager.cpp" line="376"/>
        <location filename="NotesManager.cpp" line="372"/>
        <location filename="NotesManager.cpp" line="372"/>
        <source>Mains power</source>
        <translation>Netzbetrieb</translation>
    </message>
    <message>
        <location filename="NotesManager.cpp" line="304"/>
        <location filename="NotesManager.cpp" line="304"/>
        <location filename="NotesManager.cpp" line="304"/>
        <location filename="NotesManager.cpp" line="304"/>
        <location filename="NotesManager.cpp" line="306"/>
        <location filename="NotesManager.cpp" line="306"/>
        <location filename="NotesManager.cpp" line="306"/>
        <location filename="NotesManager.cpp" line="306"/>
        <location filename="NotesManager.cpp" line="306"/>
        <location filename="NotesManager.cpp" line="306"/>
        <location filename="NotesManager.cpp" line="306"/>
        <location filename="NotesManager.cpp" line="306"/>
        <location filename="NotesManager.cpp" line="306"/>
        <location filename="NotesManager.cpp" line="308"/>
        <location filename="NotesManager.cpp" line="308"/>
        <location filename="NotesManager.cpp" line="308"/>
        <location filename="NotesManager.cpp" line="310"/>
        <location filename="NotesManager.cpp" line="308"/>
        <location filename="NotesManager.cpp" line="308"/>
        <location filename="NotesManager.cpp" line="305"/>
        <location filename="NotesManager.cpp" line="305"/>
        <location filename="NotesManager.cpp" line="305"/>
        <location filename="NotesManager.cpp" line="305"/>
        <location filename="NotesManager.cpp" line="307"/>
        <location filename="NotesManager.cpp" line="307"/>
        <location filename="NotesManager.cpp" line="307"/>
        <location filename="NotesManager.cpp" line="307"/>
        <location filename="NotesManager.cpp" line="307"/>
        <location filename="NotesManager.cpp" line="307"/>
        <location filename="NotesManager.cpp" line="309"/>
        <location filename="NotesManager.cpp" line="309"/>
        <location filename="NotesManager.cpp" line="309"/>
        <location filename="NotesManager.cpp" line="329"/>
        <location filename="NotesManager.cpp" line="329"/>
        <location filename="NotesManager.cpp" line="329"/>
        <location filename="NotesManager.cpp" line="329"/>
        <location filename="NotesManager.cpp" line="329"/>
        <location filename="NotesManager.cpp" line="329"/>
        <location filename="NotesManager.cpp" line="329"/>
        <location filename="NotesManager.cpp" line="329"/>
        <location filename="NotesManager.cpp" line="329"/>
        <location filename="NotesManager.cpp" line="329"/>
        <location filename="NotesManager.cpp" line="329"/>
        <location filename="NotesManager.cpp" line="329"/>
        <location filename="NotesManager.cpp" line="329"/>
        <location filename="NotesManager.cpp" line="329"/>
        <location filename="NotesManager.cpp" line="329"/>
        <location filename="NotesManager.cpp" line="329"/>
        <location filename="NotesManager.cpp" line="329"/>
        <location filename="NotesManager.cpp" line="329"/>
        <location filename="NotesManager.cpp" line="329"/>
        <location filename="NotesManager.cpp" line="329"/>
        <location filename="NotesManager.cpp" line="329"/>
        <location filename="NotesManager.cpp" line="329"/>
        <location filename="NotesManager.cpp" line="329"/>
        <location filename="NotesManager.cpp" line="329"/>
        <location filename="NotesManager.cpp" line="329"/>
        <location filename="NotesManager.cpp" line="329"/>
        <location filename="NotesManager.cpp" line="329"/>
        <location filename="NotesManager.cpp" line="329"/>
        <location filename="NotesManager.cpp" line="329"/>
        <location filename="NotesManager.cpp" line="329"/>
        <location filename="NotesManager.cpp" line="329"/>
        <location filename="NotesManager.cpp" line="329"/>
        <location filename="NotesManager.cpp" line="329"/>
        <location filename="NotesManager.cpp" line="329"/>
        <location filename="NotesManager.cpp" line="329"/>
        <location filename="NotesManager.cpp" line="329"/>
        <location filename="NotesManager.cpp" line="329"/>
        <location filename="NotesManager.cpp" line="329"/>
        <location filename="NotesManager.cpp" line="329"/>
        <location filename="NotesManager.cpp" line="329"/>
        <location filename="NotesManager.cpp" line="329"/>
        <location filename="NotesManager.cpp" line="329"/>
        <location filename="NotesManager.cpp" line="329"/>
        <location filename="NotesManager.cpp" line="329"/>
        <location filename="NotesManager.cpp" line="361"/>
        <location filename="NotesManager.cpp" line="361"/>
        <location filename="NotesManager.cpp" line="308"/>
        <location filename="NotesManager.cpp" line="308"/>
        <location filename="NotesManager.cpp" line="308"/>
        <location filename="NotesManager.cpp" line="299"/>
        <location filename="NotesManager.cpp" line="299"/>
        <location filename="NotesManager.cpp" line="299"/>
        <location filename="NotesManager.cpp" line="299"/>
        <location filename="NotesManager.cpp" line="299"/>
        <location filename="NotesManager.cpp" line="299"/>
        <location filename="NotesManager.cpp" line="299"/>
        <location filename="NotesManager.cpp" line="312"/>
        <location filename="NotesManager.cpp" line="312"/>
        <location filename="NotesManager.cpp" line="313"/>
        <location filename="NotesManager.cpp" line="313"/>
        <location filename="NotesManager.cpp" line="334"/>
        <location filename="NotesManager.cpp" line="334"/>
        <location filename="NotesManager.cpp" line="335"/>
        <location filename="NotesManager.cpp" line="335"/>
        <location filename="NotesManager.cpp" line="336"/>
        <location filename="NotesManager.cpp" line="336"/>
        <location filename="NotesManager.cpp" line="339"/>
        <location filename="NotesManager.cpp" line="360"/>
        <location filename="NotesManager.cpp" line="360"/>
        <location filename="NotesManager.cpp" line="360"/>
        <location filename="NotesManager.cpp" line="357"/>
        <location filename="NotesManager.cpp" line="357"/>
        <location filename="NotesManager.cpp" line="357"/>
        <location filename="NotesManager.cpp" line="357"/>
        <location filename="NotesManager.cpp" line="357"/>
        <location filename="NotesManager.cpp" line="357"/>
        <location filename="NotesManager.cpp" line="361"/>
        <location filename="NotesManager.cpp" line="361"/>
        <location filename="NotesManager.cpp" line="361"/>
        <location filename="NotesManager.cpp" line="362"/>
        <location filename="NotesManager.cpp" line="362"/>
        <location filename="NotesManager.cpp" line="362"/>
        <location filename="NotesManager.cpp" line="362"/>
        <location filename="NotesManager.cpp" line="362"/>
        <location filename="NotesManager.cpp" line="362"/>
        <location filename="NotesManager.cpp" line="362"/>
        <location filename="NotesManager.cpp" line="362"/>
        <location filename="NotesManager.cpp" line="363"/>
        <location filename="NotesManager.cpp" line="363"/>
        <location filename="NotesManager.cpp" line="365"/>
        <location filename="NotesManager.cpp" line="365"/>
        <location filename="NotesManager.cpp" line="364"/>
        <location filename="NotesManager.cpp" line="363"/>
        <location filename="NotesManager.cpp" line="363"/>
        <location filename="NotesManager.cpp" line="363"/>
        <location filename="NotesManager.cpp" line="365"/>
        <location filename="NotesManager.cpp" line="365"/>
        <location filename="NotesManager.cpp" line="367"/>
        <location filename="NotesManager.cpp" line="367"/>
        <location filename="NotesManager.cpp" line="367"/>
        <location filename="NotesManager.cpp" line="367"/>
        <location filename="NotesManager.cpp" line="365"/>
        <location filename="NotesManager.cpp" line="365"/>
        <location filename="NotesManager.cpp" line="372"/>
        <location filename="NotesManager.cpp" line="372"/>
        <location filename="NotesManager.cpp" line="372"/>
        <location filename="NotesManager.cpp" line="372"/>
        <location filename="NotesManager.cpp" line="368"/>
        <location filename="NotesManager.cpp" line="368"/>
        <location filename="NotesManager.cpp" line="368"/>
        <location filename="NotesManager.cpp" line="368"/>
        <location filename="NotesManager.cpp" line="368"/>
        <location filename="NotesManager.cpp" line="368"/>
        <location filename="NotesManager.cpp" line="368"/>
        <location filename="NotesManager.cpp" line="368"/>
        <location filename="NotesManager.cpp" line="368"/>
        <location filename="NotesManager.cpp" line="368"/>
        <location filename="NotesManager.cpp" line="368"/>
        <location filename="NotesManager.cpp" line="368"/>
        <location filename="NotesManager.cpp" line="368"/>
        <location filename="NotesManager.cpp" line="368"/>
        <location filename="NotesManager.cpp" line="368"/>
        <location filename="NotesManager.cpp" line="368"/>
        <location filename="NotesManager.cpp" line="368"/>
        <location filename="NotesManager.cpp" line="368"/>
        <location filename="NotesManager.cpp" line="368"/>
        <location filename="NotesManager.cpp" line="368"/>
        <location filename="NotesManager.cpp" line="368"/>
        <location filename="NotesManager.cpp" line="368"/>
        <location filename="NotesManager.cpp" line="368"/>
        <location filename="NotesManager.cpp" line="368"/>
        <location filename="NotesManager.cpp" line="368"/>
        <location filename="NotesManager.cpp" line="368"/>
        <location filename="NotesManager.cpp" line="368"/>
        <location filename="NotesManager.cpp" line="376"/>
        <location filename="NotesManager.cpp" line="384"/>
        <location filename="NotesManager.cpp" line="384"/>
        <location filename="NotesManager.cpp" line="385"/>
        <location filename="NotesManager.cpp" line="385"/>
        <location filename="NotesManager.cpp" line="382"/>
        <location filename="NotesManager.cpp" line="382"/>
        <location filename="NotesManager.cpp" line="386"/>
        <location filename="NotesManager.cpp" line="386"/>
        <location filename="NotesManager.cpp" line="386"/>
        <location filename="NotesManager.cpp" line="386"/>
        <location filename="NotesManager.cpp" line="386"/>
        <location filename="NotesManager.cpp" line="386"/>
        <location filename="NotesManager.cpp" line="386"/>
        <location filename="NotesManager.cpp" line="384"/>
        <location filename="NotesManager.cpp" line="384"/>
        <location filename="NotesManager.cpp" line="388"/>
        <location filename="NotesManager.cpp" line="388"/>
        <location filename="NotesManager.cpp" line="390"/>
        <location filename="NotesManager.cpp" line="390"/>
        <location filename="NotesManager.cpp" line="395"/>
        <location filename="NotesManager.cpp" line="395"/>
        <location filename="NotesManager.cpp" line="394"/>
        <location filename="NotesManager.cpp" line="394"/>
        <location filename="NotesManager.cpp" line="394"/>
        <location filename="NotesManager.cpp" line="396"/>
        <location filename="NotesManager.cpp" line="396"/>
        <location filename="NotesManager.cpp" line="394"/>
        <location filename="NotesManager.cpp" line="394"/>
        <location filename="NotesManager.cpp" line="396"/>
        <location filename="NotesManager.cpp" line="396"/>
        <location filename="NotesManager.cpp" line="397"/>
        <location filename="NotesManager.cpp" line="376"/>
        <location filename="NotesManager.cpp" line="372"/>
        <location filename="NotesManager.cpp" line="372"/>
        <source>Battery powered (%1%)</source>
        <translation>Batteriebetrieb (%1%)</translation>
    </message>
    <message>
        <location filename="NotesManager.cpp" line="371"/>
        <location filename="NotesManager.cpp" line="371"/>
        <location filename="NotesManager.cpp" line="371"/>
        <location filename="NotesManager.cpp" line="371"/>
        <location filename="NotesManager.cpp" line="371"/>
        <location filename="NotesManager.cpp" line="372"/>
        <location filename="NotesManager.cpp" line="372"/>
        <location filename="NotesManager.cpp" line="374"/>
        <location filename="NotesManager.cpp" line="374"/>
        <location filename="NotesManager.cpp" line="373"/>
        <location filename="NotesManager.cpp" line="372"/>
        <location filename="NotesManager.cpp" line="372"/>
        <location filename="NotesManager.cpp" line="372"/>
        <location filename="NotesManager.cpp" line="374"/>
        <location filename="NotesManager.cpp" line="374"/>
        <location filename="NotesManager.cpp" line="376"/>
        <location filename="NotesManager.cpp" line="376"/>
        <location filename="NotesManager.cpp" line="376"/>
        <location filename="NotesManager.cpp" line="376"/>
        <location filename="NotesManager.cpp" line="374"/>
        <location filename="NotesManager.cpp" line="374"/>
        <location filename="NotesManager.cpp" line="381"/>
        <location filename="NotesManager.cpp" line="381"/>
        <location filename="NotesManager.cpp" line="381"/>
        <location filename="NotesManager.cpp" line="381"/>
        <location filename="NotesManager.cpp" line="377"/>
        <location filename="NotesManager.cpp" line="377"/>
        <location filename="NotesManager.cpp" line="377"/>
        <location filename="NotesManager.cpp" line="377"/>
        <location filename="NotesManager.cpp" line="377"/>
        <location filename="NotesManager.cpp" line="377"/>
        <location filename="NotesManager.cpp" line="377"/>
        <location filename="NotesManager.cpp" line="377"/>
        <location filename="NotesManager.cpp" line="377"/>
        <location filename="NotesManager.cpp" line="377"/>
        <location filename="NotesManager.cpp" line="377"/>
        <location filename="NotesManager.cpp" line="377"/>
        <location filename="NotesManager.cpp" line="377"/>
        <location filename="NotesManager.cpp" line="377"/>
        <location filename="NotesManager.cpp" line="378"/>
        <location filename="NotesManager.cpp" line="378"/>
        <location filename="NotesManager.cpp" line="378"/>
        <location filename="NotesManager.cpp" line="378"/>
        <location filename="NotesManager.cpp" line="378"/>
        <location filename="NotesManager.cpp" line="378"/>
        <location filename="NotesManager.cpp" line="378"/>
        <location filename="NotesManager.cpp" line="378"/>
        <location filename="NotesManager.cpp" line="378"/>
        <location filename="NotesManager.cpp" line="378"/>
        <location filename="NotesManager.cpp" line="378"/>
        <location filename="NotesManager.cpp" line="378"/>
        <location filename="NotesManager.cpp" line="378"/>
        <location filename="NotesManager.cpp" line="386"/>
        <location filename="NotesManager.cpp" line="394"/>
        <location filename="NotesManager.cpp" line="394"/>
        <location filename="NotesManager.cpp" line="395"/>
        <location filename="NotesManager.cpp" line="395"/>
        <location filename="NotesManager.cpp" line="392"/>
        <location filename="NotesManager.cpp" line="392"/>
        <location filename="NotesManager.cpp" line="396"/>
        <location filename="NotesManager.cpp" line="396"/>
        <location filename="NotesManager.cpp" line="396"/>
        <location filename="NotesManager.cpp" line="396"/>
        <location filename="NotesManager.cpp" line="396"/>
        <location filename="NotesManager.cpp" line="396"/>
        <location filename="NotesManager.cpp" line="396"/>
        <location filename="NotesManager.cpp" line="394"/>
        <location filename="NotesManager.cpp" line="394"/>
        <location filename="NotesManager.cpp" line="398"/>
        <location filename="NotesManager.cpp" line="398"/>
        <location filename="NotesManager.cpp" line="400"/>
        <location filename="NotesManager.cpp" line="400"/>
        <location filename="NotesManager.cpp" line="405"/>
        <location filename="NotesManager.cpp" line="405"/>
        <location filename="NotesManager.cpp" line="404"/>
        <location filename="NotesManager.cpp" line="404"/>
        <location filename="NotesManager.cpp" line="404"/>
        <location filename="NotesManager.cpp" line="406"/>
        <location filename="NotesManager.cpp" line="406"/>
        <location filename="NotesManager.cpp" line="404"/>
        <location filename="NotesManager.cpp" line="404"/>
        <location filename="NotesManager.cpp" line="406"/>
        <location filename="NotesManager.cpp" line="406"/>
        <location filename="NotesManager.cpp" line="407"/>
        <location filename="NotesManager.cpp" line="386"/>
        <location filename="NotesManager.cpp" line="382"/>
        <location filename="NotesManager.cpp" line="382"/>
        <source>Backup Notes - %1</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="NotesManager.cpp" line="417"/>
        <location filename="NotesManager.cpp" line="417"/>
        <location filename="NotesManager.cpp" line="417"/>
        <location filename="NotesManager.cpp" line="417"/>
        <location filename="NotesManager.cpp" line="416"/>
        <location filename="NotesManager.cpp" line="416"/>
        <source>Backup to USB complete (%1 files saved)</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="NotesManager.cpp" line="409"/>
        <location filename="NotesManager.cpp" line="409"/>
        <source>Backup: %1</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="NotesManager.cpp" line="153"/>
        <location filename="NotesManager.cpp" line="153"/>
        <location filename="NotesManager.cpp" line="154"/>
        <location filename="NotesManager.cpp" line="154"/>
        <location filename="NotesManager.cpp" line="157"/>
        <location filename="NotesManager.cpp" line="157"/>
        <location filename="NotesManager.cpp" line="157"/>
        <location filename="NotesManager.cpp" line="157"/>
        <location filename="NotesManager.cpp" line="157"/>
        <location filename="NotesManager.cpp" line="157"/>
        <location filename="NotesManager.cpp" line="157"/>
        <location filename="NotesManager.cpp" line="157"/>
        <location filename="NotesManager.cpp" line="157"/>
        <location filename="NotesManager.cpp" line="157"/>
        <location filename="NotesManager.cpp" line="157"/>
        <location filename="NotesManager.cpp" line="157"/>
        <location filename="NotesManager.cpp" line="157"/>
        <location filename="NotesManager.cpp" line="157"/>
        <location filename="NotesManager.cpp" line="157"/>
        <source>Backup to USB complete</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>TopicWidget</name>
    <message>
        <location filename="TopicWidget.ui" line="14"/>
        <location filename="TopicWidget.ui" line="14"/>
        <source>Form</source>
        <translation></translation>
    </message>
    <message>
        <location filename="TopicWidget.ui" line="54"/>
        <location filename="TopicWidget.ui" line="54"/>
        <source>Save topic name</source>
        <translation>Unterrichtsfach umbenennen</translation>
    </message>
    <message>
        <location filename="TopicWidget.ui" line="97"/>
        <location filename="TopicWidget.ui" line="97"/>
        <source>Change topic name</source>
        <translation>Unterrichtsfach umbenennen</translation>
    </message>
    <message>
        <location filename="TopicWidget.ui" line="115"/>
        <location filename="TopicWidget.ui" line="115"/>
        <source>Neue Notiz hinzufügen</source>
        <translation>Neue Mitschrift hinzufügen</translation>
    </message>
</context>
</TS>
